import * as React from "react"
import type { HeadFC, PageProps } from "gatsby"
import styled from "styled-components";
import image1 from "../images/image1.png"

const Main = styled.main`
  font-family: Futura,Arial,sans-serif;
  height: 100dvh;
`

const BackgroundImage = styled.div`
  overflow: hidden;
  //height: 100dvh;
  height: 100%;
  background-image: url(${image1});
  background-size: cover;
  background-position: center;
  opacity: 0;
  animation: fadeIn 1s linear 0.25s 1 forwards;
  @keyframes fadeIn { /*animation-nameで設定した値を書く*/
    0% {opacity: 0} /*アニメーション開始時は不透明度0%*/
    100% {opacity: 1} /*アニメーション終了時は不透明度100%*/
  }
`;

const ContentBox = styled.div`
  font-weight: 100;
  opacity: 0.9;
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translateY(-50%) translateX(-50%);
  letter-spacing: 0.1rem;
  font-style: italic;
`

const Title = styled.h1`
  color: white;
  font-size: 60px;
  font-weight: 100;
  letter-spacing: 0.2rem;
`

const SubTitle = styled.h2`
  color: white;
  opacity: 0.85;
  font-size: 18px;
  font-weight: 100;
`

const Description = styled.p`
  color: white;
  opacity: 0.85;
  font-size: 14px;
`

const Bottom = styled.div`
  color: white;
  font-size: 12px;
  font-weight: 100;
  position: absolute;
  bottom: 1%;
  right: 1%;
  opacity: 0.6;
  text-align: right;
  font-style: italic;
`

const IndexPage: React.FC<PageProps> = () => {
  return (
    <Main>
        <BackgroundImage>
            <ContentBox>
                <Title>touyu.me</Title>
                <SubTitle>Yuto Akiba</SubTitle>
                <Description>Software Engineer</Description>
            </ContentBox>
            <Bottom>
                <p>"A cyberpunk beautiful scenery of Kyoto"</p>
                <p>generated by DALL・E</p>
            </Bottom>
        </BackgroundImage>
    </Main>
  )
}

export default IndexPage

export const Head: HeadFC = () => <title>touyu.me</title>
