import Head from 'next/head'
import styled from "styled-components";

const Main = styled.main`
  font-family: Futura,Arial,sans-serif;
  height: 100dvh;
`

const BackgroundImage = styled.div`
  height: 100%;
  background-image: url('/touyu_many_computers_piles_miscellaneous_placed_deconstructed_d_59ecf491-e4ad-42be-821f-a19f3537f808.png');
  background-size: cover;
  background-repeat: no-repeat;
  background-position: center;
  opacity: 0;
  animation: fadeIn 1s linear 0.25s 1 forwards;
  @keyframes fadeIn { /*animation-nameで設定した値を書く*/
    0% {opacity: 0} /*アニメーション開始時は不透明度0%*/
    100% {opacity: 1} /*アニメーション終了時は不透明度100%*/
  }
`;

const BackgroundOverlay = styled.div`
  margin: 0;
  background: rgba(0,0,0,0);
  width: 100%;
  height: 100%;
`

const ContentBox = styled.div`
  font-weight: 100;
  opacity: 0.9;
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translateY(-50%) translateX(-50%);
  letter-spacing: 0.1rem;
  font-style: italic;
`

const Title = styled.h1`
  color: white;
  font-size: 60px;
  font-weight: 100;
  letter-spacing: 0.2rem;
`

const SubTitle = styled.h2`
  color: white;
  font-size: 18px;
  font-weight: 100;
`

const Description = styled.p`
  color: white;
  opacity: 0.9;
  font-size: 14px;
`

const RightBottom = styled.div`
  color: white;
  font-size: 12px;
  font-weight: 100;
  position: absolute;
  bottom: 1%;
  right: 1%;
  opacity: 0.7;
  text-align: right;
  font-style: italic;
  max-width: 80%;
`

const SocialLink = styled.a`
  //text-decoration: underline;
  position: relative;
  font-size: 12px;
  background-image: linear-gradient(0deg, white, white); /* 線の色 */
  background-repeat: no-repeat;
  background-position: left bottom; /* 線の起点を左・下に設定 */
  background-size: 0 1px; /* 線の横幅を0、縦幅を1pxに */
  transition: background-size 0.3s;
  &:hover{
    background-size: 100% 1px;
  }
`

const SocialContainer = styled.div`
  margin-top: 16px;
  display: flex;
  column-gap: 16px;
  
`

export default function Home() {
  return (
    <>
      <Head>
          <title>touyu.me</title>
          <meta name="touyu.me" content="touyu.me" />
          <meta property="og:url" content="https://touyu.me" />
          <meta property="og:type" content="website" />
          <meta property="og:site_name" content="touyu.me" />
          <meta property="og:title" content="touyu.me" />
          <meta property="og:description" content="touyu.me" />
          <meta property="og:image" content="https://touyu.me/ogp.png" />

          {/* Twitter */}
          <meta name="twitter:card" content="summary_large_image" />
          <meta name="twitter:site" content="@akkey0222" />
      </Head>
      <Main>
          <BackgroundImage>
              <BackgroundOverlay>
                  <ContentBox>
                      <Title>touyu.me</Title>
                      <SubTitle>Yuto Akiba</SubTitle>
                      <Description>Software Engineer</Description>
                      <SocialContainer>
                          <SocialLink href="https://github.com/touyu">GitHub</SocialLink>
                          <SocialLink href="https://twitter.com/akkey0222">Twitter</SocialLink>
                      </SocialContainer>
                  </ContentBox>
                  <RightBottom>
                      <p>"many computers, piles, miscellaneous placed, deconstructed, deep sea, 8K --ar 3:2 --q 5"</p>
                      <p>generated by Midjourney</p>
                  </RightBottom>
              </BackgroundOverlay>
          </BackgroundImage>
      </Main>
    </>
  )
}
