import styled from "styled-components";
import {siteData, backgroundImages} from "./model/data";
import type {BackgroundImage} from "./model/data";

const Main = styled.main`
  font-family: Futura,Arial,sans-serif;
  height: 100dvh;
`

const BackgroundImageContainer = styled.div<{ path: string }>`
  height: 100%;
  background-image: url(${(props) => props.path});
  background-size: cover;
  background-repeat: no-repeat;
  background-position: center;
  opacity: 0;
  animation: fadeIn 1s linear 0.25s 1 forwards;
  @keyframes fadeIn {
    0% {opacity: 0}
    100% {opacity: 1}
  }
`;

const BackgroundOverlay = styled.div`
  margin: 0;
  background: rgba(0,0,0,0);
  width: 100%;
  height: 100%;
`

const ContentBox = styled.div`
  font-weight: 100;
  opacity: 0.9;
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translateY(-50%) translateX(-50%);
  letter-spacing: 0.1rem;
  font-style: italic;
`

const Title = styled.h1`
  color: white;
  font-size: 60px;
  font-weight: 100;
  letter-spacing: 0.2rem;
`

const SubTitle = styled.h2`
  margin-top: 8px;
  color: white;
  font-size: 18px;
  font-weight: 100;
`

const Description = styled.p`
  color: white;
  opacity: 0.9;
  font-size: 14px;
`

const RightBottom = styled.div`
  color: white;
  font-size: 12px;
  font-weight: 100;
  position: absolute;
  bottom: 1%;
  right: 1%;
  opacity: 0.7;
  text-align: right;
  font-style: italic;
  max-width: 80%;
`

const SocialLink = styled.a`
  position: relative;
  font-size: 12px;
  background-image: linear-gradient(0deg, white, white); /* 線の色 */
  background-repeat: no-repeat;
  background-position: left bottom; /* 線の起点を左・下に設定 */
  background-size: 0 1px; /* 線の横幅を0、縦幅を1pxに */
  transition: background-size 0.3s;
  &:hover{
    background-size: 100% 1px;
  }
`

const SocialContainer = styled.div`
  margin-top: 12px;
  display: flex;
  column-gap: 16px;
`

function getBackgroundImage(): BackgroundImage {
  return backgroundImages[Math.floor(Math.random() * backgroundImages.length)]
}

const backgroundImage = getBackgroundImage()

const App = () => {
  return (
    <Main>
      <BackgroundImageContainer path={backgroundImage.path}>
        <BackgroundOverlay>
          <ContentBox>
            <Title>{siteData.title}</Title>
            <SubTitle>{siteData.subTitle}</SubTitle>
            <Description>{siteData.description}</Description>
            <SocialContainer>
              <SocialLink href={siteData.githubUrl}>GitHub</SocialLink>
              <SocialLink href={siteData.twitterUrl}>Twitter</SocialLink>
            </SocialContainer>
          </ContentBox>
          <RightBottom>
            <p>{backgroundImage.prompt}</p>
            <p>generated by {backgroundImage.generatedBy}</p>
          </RightBottom>
        </BackgroundOverlay>
      </BackgroundImageContainer>
    </Main>
  )
}

export default App
